# Default configuration for loom
# (No dev_root or foundry_dir here; these are user-specific)

defaults:
  git_timeout: 30
  parallel_operations: true
  log_level: INFO

# Git configuration
git:
  default_branch: main
  fetch_prune: true
  depth: 1  # For shallow clones

# Display settings
display:
  show_progress: true
  colors: true
  max_width: 80
  show_commands_on_status: false 