repos:
- name: crucible
  url: https://github.com/jazzydog-labs/crucible.git
  path: $DEV_ROOT/$FOUNDRY_DIR/crucible

- name: foundry-bootstrap
  url: https://github.com/jazzydog-labs/foundry-bootstrap.git
  path: $DEV_ROOT/$FOUNDRY_DIR/foundry-bootstrap

- name: ledger
  url: https://github.com/jazzydog-labs/ledger.git
  path: $DEV_ROOT/$FOUNDRY_DIR/ledger

- name: vault
  url: https://github.com/jazzydog-labs/vault.git
  path: $DEV_ROOT/$FOUNDRY_DIR/vault

- name: forge
  url: https://github.com/jazzydog-labs/forge.git
  path: $DEV_ROOT/$FOUNDRY_DIR/forge

- name: genesis
  url: https://github.com/jazzydog-labs/genesis.git
  path: $DEV_ROOT/genesis

- name: golden-snapshot
  url: https://github.com/jazzydog-labs/golden-snapshot.git
  path: $DEV_ROOT/golden-snapshot

- name: loom
  url: https://github.com/jazzydog-labs/loom.git
  path: $DEV_ROOT/$FOUNDRY_DIR/loom

- name: just-aliases
  url: https://github.com/jazzydog-labs/just-aliases.git
  path: $DEV_ROOT/$FOUNDRY_DIR/just-aliases

- name: bill-of-materials
  url: https://github.com/jazzydog-labs/bill-of-materials.git
  path: $DEV_ROOT/$FOUNDRY_DIR/bill-of-materials

- name: panorama
  url: https://github.com/jazzydog-labs/panorama.git
  path: $DEV_ROOT/$FOUNDRY_DIR/panorama

- name: riverrun
  url: https://github.com/jazzydog-labs/riverrun.git
  path: $DEV_ROOT/$FOUNDRY_DIR/riverrun 